export const projectList = [
  {
    id: 0,
    title: "Yanyangirl",
    img: "https://pic.pimg.tw/yangun410/1662299898-1587859911-g_b.png",
    src: "https://yangunli.github.io/yanyangirl/",
    code: "https://github.com/Yangunli/yanyangirl",
    react: "REACT",
    css: "MUI",
    paw: "PAW",
    desc: "",
  },
  {
    id: 7,
    title: "Countdown Timer",
    img: "https://pic.pimg.tw/yangun410/1662298232-641699677-g_n.png",
    src: "https://yangunli.github.io/HTML-CSS-JavaScript-projects/countdown-timer/index.html",
    code: "https://github.com/Yangunli/HTML-CSS-JavaScript-projects/tree/gh-pages/countdown-timer",
    info: "123",
    css: "CSS",
    js: "Java Script",
    desc: "",
  },
  {
    id: 6,
    title: "Simple Caculator",
    img: "https://pic.pimg.tw/yangun410/1662298232-3559462788-g_n.png",
    src: "https://yangunli.github.io/HTML-CSS-JavaScript-projects/caculator/index.html",
    code: "https://github.com/Yangunli/HTML-CSS-JavaScript-projects/tree/gh-pages/caculator",
    info: "123",
    css: "CSS",
    js: "Java Script",
    desc: "",
  },
  {
    id: 5,
    title: "todoList",
    img: "https://pic.pimg.tw/yangun410/1662291160-1202080164-g_n.png",
    src: "https://yangunli.github.io/todoList/",
    code: "https://github.com/Yangunli/todoList",
    info: "123",
    css: "CSS",
    paw: "PAW",
    react: "REACT",
    desc: "",
  },
  {
    id: 4,
    title: "shopping cart",
    img: "https://pic.pimg.tw/yangun410/1662291160-1815824603-g_n.png",
    src: "https://yangunli.github.io/eshopping-cart/",
    code: "https://github.com/Yangunli/eshopping-cart",
    info: "",
    react: "REACT",
    css: "Bootstrap",
    desc: "123",
  },
  {
    id: 3,
    title: "Kaohsiung Travel",
    img: "https://pic.pimg.tw/yangun410/1662291161-579906337-g_n.png",
    src: "https://yangunli.github.io/haveaniceday/",
    code: "https://github.com/Yangunli/haveaniceday",
    info: "",
    react: "REACT",
    css: "CSS",
    paw: "PAW",
    desc: "",
  },
  {
    id: 2,
    title: "MediaHub APP",
    img: "https://pic.pimg.tw/yangun410/1662291161-2631840629-g_n.png",
    src: "https://yangunli.github.io/mediahub-app/",
    code: "https://github.com/Yangunli/mediahub-app",
    info: "",
    css: "MUI",
    react: "REACT",
    paw: "PAW",
    desc: "",
  },
  {
    id: 1,
    title: "Realtime Weather APP",
    img: "https://pic.pimg.tw/yangun410/1662291160-1463751798-g_n.png?v=1662291162",
    src: "https://yangunli.github.io/weather-app/",
    code: "https://github.com/Yangunli/weather-app",
    info: "",
    react: "REACT",
    css: "Emotion/css",
    paw: "PAW",
    desc: "",
  },
];
