export const projectList = [
  {
    id: 0,
    title: "Yanyangirl",
    img: "https://pic.pimg.tw/yangun410/1662299898-1587859911-g_b.png",
    src: "https://yangunli.github.io/yanyangirl/",
    code: "https://github.com/Yangunli/yanyangirl",
    react: "REACT",
    css: "MUI",
    pwa: "PWA",
    desc: "目前實際推出開放使用及下載的PWA網站\uff01舒服的奶茶色調\uff0c直覺地操作方式\uff0c輕鬆找出三座城市裡的展覽",
  },
  {
    id: 7,
    title: "Countdown Timer",
    img: "https://pic.pimg.tw/yangun410/1662298232-641699677-g_n.png",
    src: "https://yangunli.github.io/HTML-CSS-JavaScript-projects/countdown-timer/index.html",
    code: "https://github.com/Yangunli/HTML-CSS-JavaScript-projects/tree/gh-pages/countdown-timer",
    css: "CSS",
    js: "Java Script",
    desc: "藉由Vanilla JS\uff0c做出新年倒數的小工具",
  },
  {
    id: 6,
    title: "Simple Caculator",
    img: "https://pic.pimg.tw/yangun410/1662298232-3559462788-g_n.png",
    src: "https://yangunli.github.io/HTML-CSS-JavaScript-projects/caculator/index.html",
    code: "https://github.com/Yangunli/HTML-CSS-JavaScript-projects/tree/gh-pages/caculator",
    css: "CSS",
    js: "Java Script",
    desc: "藉由Vanilla JS\uff0c做出具有基本運算功能的計算機",
  },
  {
    id: 5,
    title: "todoList",
    img: "https://pic.pimg.tw/yangun410/1662291160-1202080164-g_n.png",
    src: "https://yangunli.github.io/todoList/",
    code: "https://github.com/Yangunli/todoList",
    info: "123",
    css: "CSS",
    pwa: "PWA",
    react: "REACT",
    desc: "以React為框架製作而成的Todo List\uff0c能夠新增刪除列表\uff0c也可以切換不同狀態",
  },
  {
    id: 4,
    title: "shopping cart",
    img: "https://pic.pimg.tw/yangun410/1662291160-1815824603-g_n.png",
    src: "https://yangunli.github.io/eshopping-cart/",
    code: "https://github.com/Yangunli/eshopping-cart",
    info: "",
    react: "REACT",
    css: "Bootstrap",
    desc: "練習React Context API及useContext Hook的使用\uff0c初次嘗試使用Bootstrap的網頁課程作品",
  },
  {
    id: 3,
    title: "HAVE A NICE DAY",
    img: "https://pic.pimg.tw/yangun410/1662446597-1288189432-g_n.png",
    src: "https://yangunli.github.io/haveaniceday/",
    code: "https://github.com/Yangunli/haveaniceday",
    react: "REACT",
    css: "CSS",
    pwa: "PWA",
    desc: "以React為框架\uff0c資料來源為使用臺北以及基隆和高雄的Open Api",
  },
  {
    id: 2,
    title: "MediaHub APP",
    img: "https://pic.pimg.tw/yangun410/1662291161-2631840629-g_n.png",
    src: "https://yangunli.github.io/mediahub-app/",
    code: "https://github.com/Yangunli/mediahub-app",
    css: "MUI",
    react: "REACT",
    pwa: "PWA",
    desc: "學習串接API和使用MUI的作品\uff0c使用的是TMDB的API",
  },
  {
    id: 1,
    title: "Realtime Weather APP",
    img: "https://pic.pimg.tw/yangun410/1662291160-1463751798-g_n.png?v=1662291162",
    src: "https://yangunli.github.io/weather-app/",
    code: "https://github.com/Yangunli/weather-app",
    react: "REACT",
    css: "Emotion/css",
    pwa: "PWA",
    desc: "初次認識HOOK\uff0c跟著PJCHEN一步一步完成的即時天氣APP",
  },
];
